## NumPy

Now it's virtually very difficult to learn all that is being taught  <br>
in one go esspecialy if this is your first time learing about any of this. <br>
The idea of conducting this workshop is so that you can get familiar with the notation <br>
and feel comfortable with the concepts and the learning strategies. <br>
I will keep the repository open so that you can always refer to this material in the future and keep on learning.

In [1]:
# This will allow you to use all of NumPy's Built-in functions
import numpy as np

In [2]:
my_list = [1,2,3,4,5,6,7]
my_list

[1, 2, 3, 4, 5, 6, 7]

In [3]:
my_array = np.asarray(my_list)
my_array

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
# What's the difference? The range of operations you can do on lists is very less than those of NumPy array
print(type(my_list), print(type(my_array)))

<class 'numpy.ndarray'>
<class 'list'> None


In [5]:
my_array.shape

(7,)

### Craeting N - Dimensional Matrices

In [7]:
nums = np.arange(0,50)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
nums_reshaped = nums.reshape(10,5)
nums_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

I want you to try the following by yourselves : 
* np.zeros((10,5))
* np.ones((3,8))